export const GETEMPLOYEE_REQUEST="GETEMPLOYEE_REQUEST";
export const GETEMPLOYEE_SUCCESS="GETEMPLOYEE_SUCCESS";
export const GETEMPLOYEE_FAILURE="GETEMPLOYEE_FAILURE";

export const ADDEMPLOYEE_REQUEST="ADDEMPLOYEE_REQUEST";
export const ADDEMPLOYEE_SUCCESS="ADDEMPLOYEE_SUCCESS";
export const ADDEMPLOYEE_FAILURE="ADDEMPLOYEE_FAILURE";
export const ADDCLEAR="ADDCLEAR";

export const DELETEEMPLOYEE_REQUEST="DELETEEMPLOYEE_REQUEST";
export const DELETEEMPLOYEE_SUCCESS="DELETEEMPLOYEE_SUCCESS";
export const DELETEEMPLOYEE_FAILURE="DELETEEMPLOYEE_FAILURE";

export const UPDATEEMPLOYEE_REQUEST="UPDATEEMPLOYEE_REQUEST";
export const UPDATEEMPLOYEE_SUCCESS="UPDATEEMPLOYEE_SUCCESS";
export const UPDATEEMPLOYEE_FAILURE="UPDATEEMPLOYEE_FAILURE";
export const EDITCLEAR="EDITCLEAR";

